### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by aarowman** [codemonstur/embedded-redis#23]
Currently no logging added - if we run into an error, all we have is the stack trace but not much context.

I'd love to see some useful info get logged, e.g.
- Which OS was detected
- Redis binary file name+location
- Success status if server started
- Failure to connect - error logging + log location, not just the exception (stack trace)
  - currently stack trace error just says "IOException: Ready pattern not found in log. Startup log:"
- I'm sure there's more

**Comment by fjosescarmona** [comment]
nice one

**Comment by codemonstur** [comment]
> Currently no logging added - if we run into an error, all we have is the stack trace but not much context.

I only want to add dependencies if I have to. Currently the library is nice and clean with 0 of them. You do have more to go on than just a stack trace. I suspect some form of callback mechanism would be best. `Consumer<String>` works well already for soutListener and serrListener.

> * Which OS was detected

You can call the detector yourself if you like: `OsArchitecture.detectOSandArchitecture()`

> * Redis binary file name+location

Most `ExecutableProvider`s will write the binary to a temp dir. The code for this is in `IO.writeResourceToExecutableFile()`. Printing this will get you a temporary file name. The providers that don't do this will execute the provided binary where it is.

> * Success status if server started

If it doesn't start you get an exception. If this mechansim were to somehow fail I'm sure any code executed to talk to the server will fail with connect errors. Whether the server started or not is obvious.

> * Failure to connect - error logging + log location, not just the exception (stack trace)
>   * currently stack trace error just says "IOException: Ready pattern not found in log. Startup log:"

In the event of the service crashing you can use the `soutListener()` and `serrListener()` calls in the `RedisServerBuilder`. When the code is working fine you don't need to see this so they are optional calls. I can't show the redis log since this would be dependent on the Redis config which doesn't come from me.

> * I'm sure there's more

I guess the PID number of the redis process. Maybe the port number it was configured to bind to. I don't know what real value that would give. So far my experience has been that people don't realize you can get the stdout and stderr of the process already.

**Comment by codemonstur** [comment]
I improved the error message that gets included in the exception. You'll now get the standard error output as well. I've also improved the readme on the SSL/TLS library issue.
