### ISSUE TITLE
libssl.3.dylib error in MacOS 14.4 and some linux

### ISSUE THREAD

**Issue by treenwang1** [codemonstur/embedded-redis#27]
We'll got error if no ExecutableProvider is used as below:
`'/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file, not in dyld cache)`

But use binaries in `https://github.com/codemonstur/embedded-redis/tree/master/src/main/binaries` it works fine. Could you please include those binaries in seperated Jar files? Or replace current binaries?

**Comment by codemonstur** [comment]
I can't replace the current binaries since they are: 1) being used by people already, 2) more authoritative, 3) safer. I specifically left those binaries out of the jar because I don't want to force people to download tons of different binaries when you only really need one. 

If you want to specifically have a binary available you can download it and put it in your resources folder. then provide a map with a path to the JarResourcesProvider.

Alternatively, you can also use the `newCachedUrlProvider()`  and feed it a URL or one of the constants in `ExecutableProvider`. The three binaries in `src/main/binaries` are in the constants `REDIS_7_2_MACOSX_14_SONOMA_HANKCP`, `REDIS_7_2_LINUX_JAMMY_X86_64`, `REDIS_7_2_LINUX_JAMMY_ARM_64`.
